### ISSUE TITLE
Not Compatible with RPi 1? [ES won't load after theme is installed]

### ISSUE THREAD

**Issue by robertybob** [RetroPie/es-theme-nbba#3]
I've tried on two occasions to install this theme through the RetroPie menu and both times I get an error message (something about font.cpp:143) and ES goes into an infinite reboot loop. Deleting the theme folder resolves the issue and no other themes cause this problem.

**Comment by robertybob** [comment]
![Image](https://www.dropbox.com/s/cn0qiyj5z6etro2/2015-09-06%2001.15.59.jpg)

**Comment by below9k** [comment]
`
EmulationStation/es-core/src/resources/Font.cpp:143: Font::FontFace::FontFace(ResourceData&&, int): Assertion '!err' failed.
Aborted (core dumped)
`

Is the error I assume - The issue is the path in each theme.xml file.
http://blog.petrockblock.com/forums/topic/nothing-but-box-art-wip/page/2/#post-104057

I'm not sure how the alternatives work other than moving their files to the base systems folders so I don't believe this applies to them. /shrug
I can make a PR for the base fixes (no alternative theme updates - maybe those should be different repos?) if you would like.

**Comment by joolswills** [comment]
adding the info from the thread here

```


To be honest I’m not entirely sure why they paths didn’t work, but ES would crash at startup with out the following changes.

nbaa theme\theme.xml
./../nbba theme -> ./

nbaa theme\sytem\theme.xml
./../../nbba theme/system -> ./

examples:
./../nbba theme/main/font.ttf -> ./main/font.ttf

./../../nbba theme/atari2600/logo.svg -> ./logo.svg
```

**Comment by joolswills** [comment]
@HerbFargus

**Comment by HerbFargus** [comment]
I'm going to start from the base release from the forum as to include the extra retropie menu bits and provide the above fixes. Then as mentioned by @below9k it might be worth looking at having each filter be its own repo

**Comment by HerbFargus** [comment]
ok @joolswills I finally got it sorted, sorry it took me so long. I just changed all the paths from the above fixes for the basic version of nbba: https://github.com/RetroPie/es-theme-nbba/pull/5  We can revisit the extra filters once Sekazi has completed the theme.
